### ISSUE TITLE
Model file of stage2.tar might be corrupted

### ISSUE THREAD

**Issue by UndecidedBoy** [lightas/CVPR2020_MANet#3]
Hello,

I tried to load the 'stage2.tar' in 'test.py':

https://github.com/lightas/CVPR2020_MANet/blob/6c1a5313b854a932cc126333e0bf6500e8c5c19e/test.py#L75-L77
 by replacing line 75 with:

```python
saved_model_dict = os.path.join(save_res_dir,'stage2.tar') 
```

But got the following error:
```bash
KeyError: "filename 'storages' not found"
```
This might indicate that the model file 'stage2.tar' file is corrupted. Do you have another model file?

Best!

**Comment by lightas** [comment]
@UndecidedBoy Sorry to make you confused. "stage2.tar" should be decompressed:  "tar -xvf stage2.tar".

**Comment by UndecidedBoy** [comment]
Oh sorry, my bad for not trying to decompress it, 

Thanks!
